[package]
name = "tinyproxy_log_digest"
version = "0.1.0"
authors = ["Mark Zhang <ace119@163.com>"]
edition = "2018"

[dependencies]
error-chain = "0.12.1"
log = "0.4.6"
env_logger = "0.6.1"
actix-web = "1.0"
askama = "0.8"
mktemp = "0.4.0"
flate2 = "1.0.7"
